### ISSUE TITLE
"Trailing commas" is only available since language version 1.4

### ISSUE THREAD

**Issue by mrshahzeb7** [Scandit/scandit-react-native-datacapture-id#1]
I dont know why but I am getting this ""Trailing commas" is only available since language version 1.4" error on every yarn/npm install, build fails after that!
then I go to three files and remove 'comma' my code runs again but when I refresh my app it crashed so I have to remove application from memory in order to run it again !

"Trailing commas" is only available since language version 1.4"

those files are
1: node_modules/scandit-react-native-datacapture-id/android/src/main/kotlin/com/scandit/datacapture/reactnative/id/data/defaults/SerializableIdCaptureDefaults.kt

2: node_modules/scandit-react-native-datacapture-id/android/src/main/kotlin/com/scandit/datacapture/reactnative/id/data/defaults/IdCaptureOverlayDefaults.kt

3:/node_modules/scandit-react-native-datacapture-id/android/src/main/kotlin/com/scandit/datacapture/reactnative/id/ScanditDataCaptureIdModule.kt

**Comment by ScanditSupport** [comment]
Hi @mrshahzeb7,

this seems to be an error connected to the Kotlin version.
Could you please check if your project satisfies the SDK requirements?
https://docs.scandit.com/data-capture-sdk/react-native/requirements.html#framework-platforms

If the issue persists, can you please reach out to us directly?
[Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)
